# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dKeyTable.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dKeyTable(object):
    def setupUi(self, dKeyTable):
        dKeyTable.setObjectName("dKeyTable")
        dKeyTable.setEnabled(True)
        dKeyTable.resize(1003, 646)
        self.centralwidget = QtWidgets.QWidget(dKeyTable)
        self.centralwidget.setObjectName("centralwidget")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setEnabled(True)
        self.table.setGeometry(QtCore.QRect(0, 0, 971, 591))
        self.table.setObjectName("table")
        self.table.setColumnCount(4)
        self.table.setRowCount(15)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(10, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(11, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(12, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(13, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(14, 3, item)
        dKeyTable.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(dKeyTable)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1003, 26))
        self.menubar.setObjectName("menubar")
        dKeyTable.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(dKeyTable)
        self.statusbar.setObjectName("statusbar")
        dKeyTable.setStatusBar(self.statusbar)

        self.retranslateUi(dKeyTable)
        QtCore.QMetaObject.connectSlotsByName(dKeyTable)

    def retranslateUi(self, dKeyTable):
        _translate = QtCore.QCoreApplication.translate
        dKeyTable.setWindowTitle(_translate("dKeyTable", "快捷键表"))
        item = self.table.verticalHeaderItem(0)
        item.setText(_translate("dKeyTable", "01"))
        item = self.table.verticalHeaderItem(1)
        item.setText(_translate("dKeyTable", "02"))
        item = self.table.verticalHeaderItem(2)
        item.setText(_translate("dKeyTable", "03"))
        item = self.table.verticalHeaderItem(3)
        item.setText(_translate("dKeyTable", "04"))
        item = self.table.verticalHeaderItem(4)
        item.setText(_translate("dKeyTable", "05"))
        item = self.table.verticalHeaderItem(5)
        item.setText(_translate("dKeyTable", "06"))
        item = self.table.verticalHeaderItem(6)
        item.setText(_translate("dKeyTable", "07"))
        item = self.table.verticalHeaderItem(7)
        item.setText(_translate("dKeyTable", "08"))
        item = self.table.verticalHeaderItem(8)
        item.setText(_translate("dKeyTable", "09"))
        item = self.table.verticalHeaderItem(9)
        item.setText(_translate("dKeyTable", "10"))
        item = self.table.verticalHeaderItem(10)
        item.setText(_translate("dKeyTable", "11"))
        item = self.table.verticalHeaderItem(11)
        item.setText(_translate("dKeyTable", "12"))
        item = self.table.verticalHeaderItem(12)
        item.setText(_translate("dKeyTable", "13"))
        item = self.table.verticalHeaderItem(13)
        item.setText(_translate("dKeyTable", "14"))
        item = self.table.verticalHeaderItem(14)
        item.setText(_translate("dKeyTable", "15"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("dKeyTable", "按钮名"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("dKeyTable", "快捷键"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("dKeyTable", "单词缩写"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("dKeyTable", "功能描述"))
        __sortingEnabled = self.table.isSortingEnabled()
        self.table.setSortingEnabled(False)
        item = self.table.item(0, 0)
        item.setText(_translate("dKeyTable", "画笔"))
        item = self.table.item(0, 1)
        item.setText(_translate("dKeyTable", "Ctrl+P"))
        item = self.table.item(0, 2)
        item.setText(_translate("dKeyTable", "pen"))
        item = self.table.item(0, 3)
        item.setText(_translate("dKeyTable", "给CV（计算机视觉）没有标注到的裂缝添加标注"))
        item = self.table.item(1, 0)
        item.setText(_translate("dKeyTable", "橡皮"))
        item = self.table.item(1, 1)
        item.setText(_translate("dKeyTable", "Ctrl+R"))
        item = self.table.item(1, 2)
        item.setText(_translate("dKeyTable", "rubber"))
        item = self.table.item(1, 3)
        item.setText(_translate("dKeyTable", "擦除错误的标注"))
        item = self.table.item(2, 0)
        item.setText(_translate("dKeyTable", "刷新"))
        item = self.table.item(2, 1)
        item.setText(_translate("dKeyTable", "Ctrl+F"))
        item = self.table.item(2, 2)
        item.setText(_translate("dKeyTable", "flash"))
        item = self.table.item(2, 3)
        item.setText(_translate("dKeyTable", "调用CV算法进行自动标注"))
        item = self.table.item(3, 0)
        item.setText(_translate("dKeyTable", "查看原图"))
        item = self.table.item(3, 1)
        item.setText(_translate("dKeyTable", "Alt"))
        item = self.table.item(3, 3)
        item.setText(_translate("dKeyTable", "查看未标注的原图。再次点击可以查看标注的效果"))
        item = self.table.item(4, 0)
        item.setText(_translate("dKeyTable", "选择文件夹"))
        item = self.table.item(4, 1)
        item.setText(_translate("dKeyTable", "Ctrl+D"))
        item = self.table.item(4, 2)
        item.setText(_translate("dKeyTable", "directory"))
        item = self.table.item(4, 3)
        item.setText(_translate("dKeyTable", "选择工作路径，设置之后下一次打开会自动从这个路径开始标注"))
        item = self.table.item(5, 0)
        item.setText(_translate("dKeyTable", "选择图片"))
        item = self.table.item(5, 1)
        item.setText(_translate("dKeyTable", "Ctrl+I"))
        item = self.table.item(5, 2)
        item.setText(_translate("dKeyTable", "image"))
        item = self.table.item(5, 3)
        item.setText(_translate("dKeyTable", "如果想选择一张图片进行标注测试，可以点击这个按钮。之后工作路径会设置为图片所在路径"))
        item = self.table.item(6, 0)
        item.setText(_translate("dKeyTable", "放弃图片"))
        item = self.table.item(6, 1)
        item.setText(_translate("dKeyTable", "Ctrl+A"))
        item = self.table.item(6, 2)
        item.setText(_translate("dKeyTable", "abandon"))
        item = self.table.item(6, 3)
        item.setText(_translate("dKeyTable", "放弃标注这张图片，程序会把这个图片移动到工作路径的“已处理原图”文件夹"))
        item = self.table.item(7, 0)
        item.setText(_translate("dKeyTable", "查看已标注"))
        item = self.table.item(7, 1)
        item.setText(_translate("dKeyTable", "Ctrl+V"))
        item = self.table.item(7, 2)
        item.setText(_translate("dKeyTable", "visualize"))
        item = self.table.item(7, 3)
        item.setText(_translate("dKeyTable", "打开一个对话框，可以查看已经标注的图片数据"))
        item = self.table.item(8, 0)
        item.setText(_translate("dKeyTable", "清除标注"))
        item = self.table.item(8, 1)
        item.setText(_translate("dKeyTable", "Ctrl+C"))
        item = self.table.item(8, 2)
        item.setText(_translate("dKeyTable", "clear"))
        item = self.table.item(8, 3)
        item.setText(_translate("dKeyTable", "把所有标注内容清除使用。如果CV表现很差，需要人工来进行标注，可以使用这个功能"))
        item = self.table.item(9, 0)
        item.setText(_translate("dKeyTable", "快捷键表"))
        item = self.table.item(9, 1)
        item.setText(_translate("dKeyTable", "Ctrl+T"))
        item = self.table.item(9, 2)
        item.setText(_translate("dKeyTable", "table"))
        item = self.table.item(9, 3)
        item.setText(_translate("dKeyTable", "打开快捷键表"))
        item = self.table.item(10, 0)
        item.setText(_translate("dKeyTable", "上一张"))
        item = self.table.item(10, 1)
        item.setText(_translate("dKeyTable", "Shift+<"))
        item = self.table.item(10, 3)
        item.setText(_translate("dKeyTable", "定位到处理之前的图片。因为软件编写难度大，所以只能向前回溯一张图片"))
        item = self.table.item(11, 0)
        item.setText(_translate("dKeyTable", "完成标注"))
        item = self.table.item(11, 1)
        item.setText(_translate("dKeyTable", "Shift+>"))
        item = self.table.item(11, 3)
        item.setText(_translate("dKeyTable", "完成这张图片的标注，打开下一张图片"))
        item = self.table.item(12, 0)
        item.setText(_translate("dKeyTable", "帮助"))
        item = self.table.item(12, 1)
        item.setText(_translate("dKeyTable", "Ctrl+H"))
        item = self.table.item(12, 2)
        item.setText(_translate("dKeyTable", "help"))
        item = self.table.item(12, 3)
        item.setText(_translate("dKeyTable", "进入软件的发布页面查看帮助（作者的博客）"))
        item = self.table.item(13, 0)
        item.setText(_translate("dKeyTable", "撤销"))
        item = self.table.item(13, 1)
        item.setText(_translate("dKeyTable", "Ctrl+Z"))
        item = self.table.item(13, 3)
        item.setText(_translate("dKeyTable", "撤销这个操作“只能撤销人工操作”"))
        item = self.table.item(14, 0)
        item.setText(_translate("dKeyTable", "重做"))
        item = self.table.item(14, 1)
        item.setText(_translate("dKeyTable", "Ctrl+Y"))
        item = self.table.item(14, 3)
        item.setText(_translate("dKeyTable", "取消撤销操作"))
        self.table.setSortingEnabled(__sortingEnabled)

