# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'labeler.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(935, 729)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMouseTracking(False)
        MainWindow.setAcceptDrops(False)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 401, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.bChooseFloder = QtWidgets.QPushButton(self.frame)
        self.bChooseFloder.setGeometry(QtCore.QRect(10, 70, 141, 28))
        self.bChooseFloder.setObjectName("bChooseFloder")
        self.bChooseImg = QtWidgets.QPushButton(self.frame)
        self.bChooseImg.setGeometry(QtCore.QRect(160, 70, 111, 28))
        self.bChooseImg.setObjectName("bChooseImg")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 41, 51))
        self.label.setObjectName("label")
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setGeometry(QtCore.QRect(340, 10, 51, 51))
        self.toolButton.setObjectName("toolButton")
        self.eDir = QtWidgets.QTextEdit(self.frame)
        self.eDir.setEnabled(False)
        self.eDir.setGeometry(QtCore.QRect(60, 10, 281, 41))
        self.eDir.setObjectName("eDir")
        self.bAmend = QtWidgets.QPushButton(self.frame)
        self.bAmend.setGeometry(QtCore.QRect(280, 70, 111, 28))
        self.bAmend.setObjectName("bAmend")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 190, 401, 171))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.bLookLabeled = QtWidgets.QPushButton(self.frame_3)
        self.bLookLabeled.setGeometry(QtCore.QRect(10, 60, 141, 41))
        self.bLookLabeled.setObjectName("bLookLabeled")
        self.bFinish = QtWidgets.QPushButton(self.frame_3)
        self.bFinish.setGeometry(QtCore.QRect(100, 127, 91, 41))
        self.bFinish.setObjectName("bFinish")
        self.bAbandon = QtWidgets.QPushButton(self.frame_3)
        self.bAbandon.setGeometry(QtCore.QRect(170, 10, 111, 28))
        self.bAbandon.setObjectName("bAbandon")
        self.bFlash = QtWidgets.QPushButton(self.frame_3)
        self.bFlash.setGeometry(QtCore.QRect(10, 10, 141, 41))
        self.bFlash.setObjectName("bFlash")
        self.cAutoFlash = QtWidgets.QCheckBox(self.frame_3)
        self.cAutoFlash.setGeometry(QtCore.QRect(210, 140, 91, 19))
        self.cAutoFlash.setObjectName("cAutoFlash")
        self.bPre = QtWidgets.QPushButton(self.frame_3)
        self.bPre.setGeometry(QtCore.QRect(10, 127, 81, 41))
        self.bPre.setObjectName("bPre")
        self.bClear = QtWidgets.QPushButton(self.frame_3)
        self.bClear.setGeometry(QtCore.QRect(170, 50, 111, 28))
        self.bClear.setObjectName("bClear")
        self.bTable = QtWidgets.QPushButton(self.frame_3)
        self.bTable.setGeometry(QtCore.QRect(170, 90, 111, 28))
        self.bTable.setObjectName("bTable")
        self.bUndo = QtWidgets.QCommandLinkButton(self.frame_3)
        self.bUndo.setGeometry(QtCore.QRect(290, 10, 91, 41))
        self.bUndo.setObjectName("bUndo")
        self.bRedo = QtWidgets.QCommandLinkButton(self.frame_3)
        self.bRedo.setGeometry(QtCore.QRect(290, 50, 91, 41))
        self.bRedo.setObjectName("bRedo")
        self.bHelp = QtWidgets.QCommandLinkButton(self.frame_3)
        self.bHelp.setGeometry(QtCore.QRect(290, 90, 91, 41))
        self.bHelp.setObjectName("bHelp")
        self.spinBox = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox.setGeometry(QtCore.QRect(310, 130, 16, 27))
        self.spinBox.setObjectName("spinBox")
        self.lable_img = QtWidgets.QLabel(self.centralwidget)
        self.lable_img.setGeometry(QtCore.QRect(420, 0, 311, 291))
        self.lable_img.setObjectName("lable_img")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(10, 539, 401, 151))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.sPen = QtWidgets.QSpinBox(self.frame_7)
        self.sPen.setGeometry(QtCore.QRect(10, 110, 46, 22))
        self.sPen.setMinimum(1)
        self.sPen.setMaximum(30)
        self.sPen.setProperty("value", 5)
        self.sPen.setObjectName("sPen")
        self.sRubber = QtWidgets.QSpinBox(self.frame_7)
        self.sRubber.setGeometry(QtCore.QRect(90, 110, 46, 22))
        self.sRubber.setMinimum(1)
        self.sRubber.setMaximum(200)
        self.sRubber.setProperty("value", 10)
        self.sRubber.setObjectName("sRubber")
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        self.label_9.setGeometry(QtCore.QRect(150, 110, 41, 16))
        self.label_9.setObjectName("label_9")
        self.sPaint = QtWidgets.QSpinBox(self.frame_7)
        self.sPaint.setGeometry(QtCore.QRect(190, 110, 51, 22))
        self.sPaint.setMinimum(500)
        self.sPaint.setMaximum(2000)
        self.sPaint.setSingleStep(50)
        self.sPaint.setObjectName("sPaint")
        self.bPaint = QtWidgets.QPushButton(self.frame_7)
        self.bPaint.setGeometry(QtCore.QRect(270, 90, 111, 31))
        self.bPaint.setObjectName("bPaint")
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        self.label_7.setGeometry(QtCore.QRect(10, 90, 55, 18))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        self.label_8.setGeometry(QtCore.QRect(90, 90, 55, 18))
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(self.frame_7)
        self.label_12.setGeometry(QtCore.QRect(10, 40, 55, 18))
        self.label_12.setObjectName("label_12")
        self.l_current_tool = QtWidgets.QLabel(self.frame_7)
        self.l_current_tool.setGeometry(QtCore.QRect(70, 40, 55, 18))
        self.l_current_tool.setObjectName("l_current_tool")
        self.l_current_tool_image = QtWidgets.QLabel(self.frame_7)
        self.l_current_tool_image.setGeometry(QtCore.QRect(160, 20, 91, 71))
        self.l_current_tool_image.setObjectName("l_current_tool_image")
        self.b_release_select = QtWidgets.QPushButton(self.frame_7)
        self.b_release_select.setGeometry(QtCore.QRect(280, 30, 80, 26))
        self.b_release_select.setObjectName("b_release_select")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 370, 401, 161))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.sErosion = QtWidgets.QSpinBox(self.tab)
        self.sErosion.setGeometry(QtCore.QRect(190, 50, 51, 22))
        self.sErosion.setMaximum(5)
        self.sErosion.setObjectName("sErosion")
        self.sSwell_2 = QtWidgets.QSpinBox(self.tab)
        self.sSwell_2.setGeometry(QtCore.QRect(190, 20, 51, 22))
        self.sSwell_2.setMaximum(5)
        self.sSwell_2.setObjectName("sSwell_2")
        self.bErosion = QtWidgets.QPushButton(self.tab)
        self.bErosion.setGeometry(QtCore.QRect(120, 50, 61, 28))
        self.bErosion.setObjectName("bErosion")
        self.bSwell = QtWidgets.QPushButton(self.tab)
        self.bSwell.setGeometry(QtCore.QRect(120, 20, 61, 28))
        self.bSwell.setObjectName("bSwell")
        self.b_down = QtWidgets.QPushButton(self.tab)
        self.b_down.setGeometry(QtCore.QRect(290, 70, 31, 28))
        self.b_down.setObjectName("b_down")
        self.b_up = QtWidgets.QPushButton(self.tab)
        self.b_up.setGeometry(QtCore.QRect(290, 10, 31, 28))
        self.b_up.setObjectName("b_up")
        self.b_left = QtWidgets.QPushButton(self.tab)
        self.b_left.setGeometry(QtCore.QRect(260, 40, 31, 28))
        self.b_left.setObjectName("b_left")
        self.b_right = QtWidgets.QPushButton(self.tab)
        self.b_right.setGeometry(QtCore.QRect(320, 40, 31, 28))
        self.b_right.setObjectName("b_right")
        self.s_step = QtWidgets.QSpinBox(self.tab)
        self.s_step.setGeometry(QtCore.QRect(190, 90, 51, 27))
        self.s_step.setMinimum(1)
        self.s_step.setMaximum(100)
        self.s_step.setObjectName("s_step")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(130, 90, 51, 31))
        self.label_13.setObjectName("label_13")
        self.cb_ansState = QtWidgets.QComboBox(self.tab)
        self.cb_ansState.setGeometry(QtCore.QRect(10, 30, 101, 26))
        self.cb_ansState.setObjectName("cb_ansState")
        self.cb_ansState.addItem("")
        self.cb_ansState.addItem("")
        self.cb_ansState.addItem("")
        self.cb_ansState.addItem("")
        self.cb_alpha = QtWidgets.QComboBox(self.tab)
        self.cb_alpha.setGeometry(QtCore.QRect(10, 80, 101, 26))
        self.cb_alpha.setObjectName("cb_alpha")
        self.cb_alpha.addItem("")
        self.cb_alpha.addItem("")
        self.cb_alpha.addItem("")
        self.cb_alpha.addItem("")
        self.cb_alpha.addItem("")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(10, 10, 55, 18))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(10, 60, 55, 18))
        self.label_15.setObjectName("label_15")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_2 = QtWidgets.QFrame(self.tab_2)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 391, 141))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.cDel = QtWidgets.QCheckBox(self.frame_2)
        self.cDel.setGeometry(QtCore.QRect(10, 50, 141, 19))
        self.cDel.setObjectName("cDel")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(130, 50, 81, 21))
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(80, 10, 41, 31))
        self.label_2.setObjectName("label_2")
        self.sConnect = QtWidgets.QSpinBox(self.frame_2)
        self.sConnect.setGeometry(QtCore.QRect(220, 50, 51, 22))
        self.sConnect.setMaximum(1000)
        self.sConnect.setSingleStep(25)
        self.sConnect.setObjectName("sConnect")
        self.sB1 = QtWidgets.QSpinBox(self.frame_2)
        self.sB1.setGeometry(QtCore.QRect(120, 10, 51, 22))
        self.sB1.setMaximum(1000)
        self.sB1.setSingleStep(25)
        self.sB1.setObjectName("sB1")
        self.cFill = QtWidgets.QCheckBox(self.frame_2)
        self.cFill.setEnabled(True)
        self.cFill.setGeometry(QtCore.QRect(10, 90, 121, 19))
        self.cFill.setMouseTracking(True)
        self.cFill.setObjectName("cFill")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 71, 31))
        self.label_4.setObjectName("label_4")
        self.sB2 = QtWidgets.QSpinBox(self.frame_2)
        self.sB2.setGeometry(QtCore.QRect(230, 10, 51, 22))
        self.sB2.setMaximum(1000)
        self.sB2.setSingleStep(25)
        self.sB2.setObjectName("sB2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(180, 10, 41, 31))
        self.label_3.setObjectName("label_3")
        self.sFill = QtWidgets.QSpinBox(self.frame_2)
        self.sFill.setGeometry(QtCore.QRect(220, 90, 51, 22))
        self.sFill.setMinimum(100)
        self.sFill.setMaximum(1000)
        self.sFill.setSingleStep(25)
        self.sFill.setObjectName("sFill")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(130, 90, 81, 21))
        self.label_10.setObjectName("label_10")
        self.sSwell = QtWidgets.QSpinBox(self.frame_2)
        self.sSwell.setGeometry(QtCore.QRect(300, 40, 51, 22))
        self.sSwell.setMaximum(5)
        self.sSwell.setObjectName("sSwell")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(300, 10, 61, 31))
        self.label_5.setObjectName("label_5")
        self.sFill_2 = QtWidgets.QSpinBox(self.frame_2)
        self.sFill_2.setGeometry(QtCore.QRect(300, 100, 51, 22))
        self.sFill_2.setMaximum(100)
        self.sFill_2.setProperty("value", 10)
        self.sFill_2.setDisplayIntegerBase(10)
        self.sFill_2.setObjectName("sFill_2")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(300, 70, 81, 31))
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.tab_2, "")
        self.e_filename = QtWidgets.QTextEdit(self.centralwidget)
        self.e_filename.setGeometry(QtCore.QRect(10, 130, 311, 31))
        self.e_filename.setObjectName("e_filename")
        self.b_openImg = QtWidgets.QPushButton(self.centralwidget)
        self.b_openImg.setGeometry(QtCore.QRect(320, 130, 80, 31))
        self.b_openImg.setObjectName("b_openImg")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.tb = QtWidgets.QToolBar(MainWindow)
        self.tb.setObjectName("tb")
        MainWindow.addToolBar(QtCore.Qt.RightToolBarArea, self.tb)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.cb_alpha.setCurrentIndex(1)
        self.cDel.clicked['bool'].connect(self.sConnect.setEnabled)
        self.cFill.clicked['bool'].connect(self.sFill.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.spinBox, self.toolButton)
        MainWindow.setTabOrder(self.toolButton, self.bAmend)
        MainWindow.setTabOrder(self.bAmend, self.bFinish)
        MainWindow.setTabOrder(self.bFinish, self.sB1)
        MainWindow.setTabOrder(self.sB1, self.bAbandon)
        MainWindow.setTabOrder(self.bAbandon, self.bLookLabeled)
        MainWindow.setTabOrder(self.bLookLabeled, self.bFlash)
        MainWindow.setTabOrder(self.bFlash, self.cAutoFlash)
        MainWindow.setTabOrder(self.cAutoFlash, self.bPre)
        MainWindow.setTabOrder(self.bPre, self.bClear)
        MainWindow.setTabOrder(self.bClear, self.bTable)
        MainWindow.setTabOrder(self.bTable, self.bUndo)
        MainWindow.setTabOrder(self.bUndo, self.bRedo)
        MainWindow.setTabOrder(self.bRedo, self.bHelp)
        MainWindow.setTabOrder(self.bHelp, self.sPen)
        MainWindow.setTabOrder(self.sPen, self.sRubber)
        MainWindow.setTabOrder(self.sRubber, self.sPaint)
        MainWindow.setTabOrder(self.sPaint, self.bPaint)
        MainWindow.setTabOrder(self.bPaint, self.b_release_select)
        MainWindow.setTabOrder(self.b_release_select, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.sErosion)
        MainWindow.setTabOrder(self.sErosion, self.sSwell_2)
        MainWindow.setTabOrder(self.sSwell_2, self.bErosion)
        MainWindow.setTabOrder(self.bErosion, self.bSwell)
        MainWindow.setTabOrder(self.bSwell, self.b_down)
        MainWindow.setTabOrder(self.b_down, self.b_up)
        MainWindow.setTabOrder(self.b_up, self.b_left)
        MainWindow.setTabOrder(self.b_left, self.b_right)
        MainWindow.setTabOrder(self.b_right, self.cDel)
        MainWindow.setTabOrder(self.cDel, self.sConnect)
        MainWindow.setTabOrder(self.sConnect, self.bChooseFloder)
        MainWindow.setTabOrder(self.bChooseFloder, self.cFill)
        MainWindow.setTabOrder(self.cFill, self.sB2)
        MainWindow.setTabOrder(self.sB2, self.sFill)
        MainWindow.setTabOrder(self.sFill, self.sSwell)
        MainWindow.setTabOrder(self.sSwell, self.sFill_2)
        MainWindow.setTabOrder(self.sFill_2, self.bChooseImg)
        MainWindow.setTabOrder(self.bChooseImg, self.eDir)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CV辅助标注器"))
        self.bChooseFloder.setText(_translate("MainWindow", "选择文件夹(D)"))
        self.bChooseImg.setText(_translate("MainWindow", "选择图片(I)"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>工作</p><p>路径</p></body></html>"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.bAmend.setText(_translate("MainWindow", "修改标注"))
        self.bLookLabeled.setText(_translate("MainWindow", "查看已标注(V)"))
        self.bFinish.setText(_translate("MainWindow", "完成标注▶"))
        self.bAbandon.setText(_translate("MainWindow", "放弃图片(A)"))
        self.bFlash.setText(_translate("MainWindow", "刷新(F)"))
        self.cAutoFlash.setText(_translate("MainWindow", "自动刷新"))
        self.bPre.setText(_translate("MainWindow", "◀上一张"))
        self.bClear.setText(_translate("MainWindow", "清除标注(C)"))
        self.bTable.setText(_translate("MainWindow", "快捷键表(T)"))
        self.bUndo.setText(_translate("MainWindow", "撤销(Z)"))
        self.bRedo.setText(_translate("MainWindow", "重做(Y)"))
        self.bHelp.setText(_translate("MainWindow", "帮助(H)"))
        self.lable_img.setText(_translate("MainWindow", "请点击‘选择文件夹’加载图片"))
        self.label_9.setText(_translate("MainWindow", "画布："))
        self.bPaint.setText(_translate("MainWindow", "刷新画布(S)"))
        self.label_7.setText(_translate("MainWindow", "画笔"))
        self.label_8.setText(_translate("MainWindow", "橡皮"))
        self.label_12.setText(_translate("MainWindow", "当前工具:"))
        self.l_current_tool.setText(_translate("MainWindow", "TextLabel"))
        self.l_current_tool_image.setText(_translate("MainWindow", "TextLabel"))
        self.b_release_select.setText(_translate("MainWindow", "释放所有选择"))
        self.bErosion.setText(_translate("MainWindow", "腐蚀>"))
        self.bSwell.setText(_translate("MainWindow", "膨胀>"))
        self.b_down.setText(_translate("MainWindow", "↓"))
        self.b_up.setText(_translate("MainWindow", "↑"))
        self.b_left.setText(_translate("MainWindow", "←"))
        self.b_right.setText(_translate("MainWindow", "→"))
        self.label_13.setText(_translate("MainWindow", "移动步长"))
        self.cb_ansState.setItemText(0, _translate("MainWindow", "edge detect"))
        self.cb_ansState.setItemText(1, _translate("MainWindow", "empty"))
        self.cb_ansState.setItemText(2, _translate("MainWindow", "keep annote"))
        self.cb_ansState.setItemText(3, _translate("MainWindow", "FCN"))
        self.cb_alpha.setItemText(0, _translate("MainWindow", "0"))
        self.cb_alpha.setItemText(1, _translate("MainWindow", "30"))
        self.cb_alpha.setItemText(2, _translate("MainWindow", "50"))
        self.cb_alpha.setItemText(3, _translate("MainWindow", "70"))
        self.cb_alpha.setItemText(4, _translate("MainWindow", "100"))
        self.label_14.setText(_translate("MainWindow", "辅助标注"))
        self.label_15.setText(_translate("MainWindow", "透明度"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.cDel.setText(_translate("MainWindow", "使用删除小块"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p>连通块阈值</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>阈值1</p></body></html>"))
        self.cFill.setText(_translate("MainWindow", "使用填充孔洞"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>边缘检测</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>阈值2</p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p>填充阈值</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>膨胀阈值</p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>油漆桶阈值</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.b_openImg.setText(_translate("MainWindow", "open"))
        self.tb.setWindowTitle(_translate("MainWindow", "toolBar"))

